In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import Ridge, RidgeCV, ElasticNet, LassoCV, LassoLarsCV
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn import svm
import lightgbm as lgb
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
import matplotlib
import matplotlib.pyplot as plt
from scipy.stats import skew
from scipy.stats.stats import pearsonr
from scipy import stats
import xgboost as xgb
from scipy.stats import norm
#from pyglmnet import GLM # Marco: need to understand how to install this 
from sklearn.preprocessing import StandardScaler
from subprocess import call
from sklearn.cross_validation import KFold

from IPython import get_ipython
get_ipython().run_line_magic('matplotlib', 'inline')

/home/obaidur/software/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

# Create Ensemble class

In [2]:
class Ensemble(object):
    def __init__(self, n_folds, stacker, base_models,seed_value):
        self.n_folds = n_folds
        self.stacker = stacker
        self.base_models = base_models
        self.seed_value = seed_value
        
    def fit_predict(self, X, y, T):
        X = np.array(X)
        y = np.array(y)
        T = np.array(T)
        
        folds = list(KFold(len(y), n_folds=self.n_folds, shuffle=True, random_state=self.seed_value))
        #folds = KFold(n_splits=self.n_folds, shuffle=True, random_state=self.seed_value)
        
        print("folds=",folds)
        
        S_train = np.zeros((X.shape[0], len(self.base_models)))
        S_test = np.zeros((T.shape[0], len(self.base_models)))
        
        for i, reg in enumerate(self.base_models):
            S_test_i = np.zeros((T.shape[0], len(folds)))
            for j, (train_idx, test_idx) in enumerate(folds):
                X_train = X[train_idx]
                y_train = y[train_idx]
                X_holdout = X[test_idx]
                # y_holdout = y[test_idx]
                reg.fit(X_train, y_train)
                y_pred = reg.predict(X_holdout)[:]
                S_train[test_idx, i] = y_pred
                S_test_i[:, j] = reg.predict(T)[:]
            S_test[:, i] = S_test_i.mean(1)
        self.stacker.fit(S_train, y)
        y_pred = self.stacker.predict(S_test)[:]
        return y_pred

# Read in the dataset

In [3]:
    
seed = 2017
nfold = 5
bmodels = ["elasticnet","et","lgb","rf","xgb"]
    
train = pd.read_csv("../data/X_train_v1.csv")
y = train['SalePrice']
X = train.loc[:,'MSSubClass':'SaleCondition_Partial']
    
test = pd.read_csv("../data/X_test_v1.csv")
id = test["Id"]
T = test.loc[:,'MSSubClass':'SaleCondition_Partial']
    
#Set the base models

base_models_name = []
for j in range(len(bmodels)):
        modelname = ("../models/single/model_" + bmodels[j] + ".py")
        print(modelname)
        base_models_name.append(modelname)

print(base_models_name)
base_models = []
    
for i, bm in enumerate(base_models_name):
        model = !grep "model =" {bm}
        model = model[0]
        model = model[12:]
        model = eval(model)
        base_models.append(model)
#print(model)
#print(base_models) 

# Set the stacker model

xgb = xgb.XGBRegressor(n_estimators=250,learning_rate=0.1,max_depth=4,min_child_weight=1,objective='reg:linear')
# Call stacking
    
ens = Ensemble(n_folds=nfold, stacker=xgb,base_models=base_models,seed_value=seed)

../models/single/model_elasticnet.py
../models/single/model_et.py
../models/single/model_lgb.py
../models/single/model_rf.py
../models/single/model_xgb.py
['../models/single/model_elasticnet.py', '../models/single/model_et.py', '../models/single/model_lgb.py', '../models/single/model_rf.py', '../models/single/model_xgb.py']

In [4]:
    
results = ens.fit_predict(X,y,T)
print("results=",results)

folds= [(array([   0,    1,    2, ..., 1438, 1439, 1440]), array([  17,   20,   25,   41,   54,   55,   56,   57,   61,   64,   93,
        100,  102,  114,  115,  116,  117,  119,  120,  123,  128,  160,
        165,  166,  168,  179,  183,  188,  189,  191,  192,  196,  213,
        216,  222,  230,  232,  235,  238,  239,  243,  257,  261,  262,
        263,  270,  271,  273,  277,  282,  296,  299,  300,  313,  317,
        319,  323,  332,  333,  350,  353,  355,  356,  358,  371,  377,
        379,  383,  389,  391,  397,  400,  401,  411,  416,  421,  423,
        426,  430,  434,  436,  441,  443,  451,  452,  457,  461,  462,
        463,  464,  465,  467,  472,  476,  480,  497,  499,  512,  516,
        534,  538,  539,  544,  546,  548,  550,  554,  558,  561,  563,
        575,  585,  609,  618,  621,  623,  632,  635,  636,  638,  640,
        644,  647,  650,  652,  656,  657,  662,  668,  669,  674,  679,
        684,  690,  693,  701,  702,  710,  711,  712,  714,  721,  723,
        727,  733,  734,  742,  743,  746,  751,  755,  757,  763,  767,
        768,  769,  773,  776,  803,  826,  835,  837,  842,  845,  847,
        852,  864,  866,  869,  870,  873,  879,  880,  882,  884,  890,
        891,  904,  905,  918,  920,  922,  932,  933,  941,  943,  954,
        962,  963,  966,  969,  977,  986,  997, 1000, 1008, 1012, 1013,
       1016, 1019, 1026, 1027, 1028, 1030, 1031, 1032, 1034, 1045, 1056,
       1059, 1060, 1061, 1067, 1082, 1091, 1092, 1096, 1110, 1120, 1136,
       1140, 1142, 1146, 1151, 1169, 1176, 1177, 1178, 1181, 1182, 1184,
       1187, 1192, 1201, 1203, 1207, 1210, 1211, 1215, 1216, 1217, 1220,
       1233, 1234, 1239, 1240, 1247, 1248, 1255, 1256, 1261, 1271, 1274,
       1278, 1282, 1295, 1296, 1302, 1315, 1324, 1326, 1327, 1339, 1340,
       1342, 1346, 1350, 1351, 1355, 1356, 1360, 1373, 1374, 1375, 1378,
       1381, 1386, 1388, 1389, 1394, 1395, 1404, 1409, 1417, 1421, 1427,
       1432, 1435, 1437])), (array([   2,    3,    4, ..., 1438, 1439, 1440]), array([   0,    1,    5,   11,   15,   18,   21,   30,   33,   36,   42,
         59,   60,   63,   67,   72,   76,   78,   82,   86,   94,   97,
        104,  106,  108,  111,  121,  134,  138,  140,  148,  149,  150,
        155,  157,  161,  162,  174,  181,  186,  190,  194,  197,  202,
        206,  207,  211,  214,  218,  219,  221,  237,  241,  247,  249,
        259,  285,  287,  288,  308,  311,  312,  314,  331,  336,  340,
        347,  351,  360,  361,  362,  363,  364,  368,  374,  375,  381,
        382,  387,  390,  396,  399,  402,  413,  414,  417,  420,  429,
        432,  433,  435,  438,  449,  460,  473,  478,  481,  482,  484,
        485,  487,  492,  501,  503,  505,  509,  510,  517,  522,  523,
        530,  536,  551,  552,  555,  556,  557,  562,  570,  571,  577,
        580,  601,  603,  605,  617,  624,  625,  639,  642,  649,  651,
        677,  687,  692,  697,  715,  717,  718,  726,  728,  735,  737,
        738,  744,  756,  758,  761,  766,  777,  779,  780,  783,  787,
        788,  791,  792,  794,  795,  797,  798,  806,  809,  810,  815,
        818,  820,  829,  834,  846,  853,  857,  859,  861,  867,  868,
        875,  876,  887,  897,  907,  912,  914,  921,  931,  936,  938,
        942,  950,  951,  980,  982,  983,  987,  989,  993,  994,  995,
        998, 1003, 1005, 1010, 1018, 1024, 1025, 1035, 1037, 1038, 1040,
       1046, 1048, 1054, 1057, 1065, 1066, 1068, 1071, 1077, 1080, 1084,
       1087, 1089, 1099, 1102, 1103, 1105, 1109, 1115, 1126, 1134, 1137,
       1152, 1156, 1168, 1174, 1179, 1180, 1183, 1186, 1188, 1189, 1193,
       1194, 1205, 1206, 1209, 1213, 1218, 1219, 1221, 1229, 1232, 1236,
       1254, 1258, 1260, 1266, 1267, 1270, 1273, 1281, 1287, 1291, 1294,
       1298, 1307, 1309, 1310, 1320, 1323, 1332, 1337, 1343, 1357, 1365,
       1367, 1384, 1390, 1393, 1396, 1398, 1400, 1406, 1412, 1413, 1414,
       1423, 1426])), (array([   0,    1,    2, ..., 1436, 1437, 1439]), array([   7,   10,   12,   19,   24,   27,   32,   34,   40,   43,   44,
         45,   48,   52,   53,   62,   71,   81,   84,   89,   92,   95,
         96,   98,  107,  118,  129,  132,  133,  136,  139,  145,  146,
        147,  151,  154,  159,  163,  164,  170,  173,  177,  182,  184,
        185,  187,  201,  210,  217,  226,  227,  229,  233,  236,  242,
        245,  246,  250,  253,  254,  266,  267,  278,  281,  283,  289,
        290,  293,  304,  305,  306,  310,  322,  324,  326,  327,  329,
        335,  339,  367,  369,  370,  376,  403,  405,  407,  412,  422,
        428,  437,  440,  442,  446,  455,  458,  468,  486,  488,  493,
        496,  498,  500,  502,  504,  507,  515,  520,  526,  527,  528,
        532,  533,  535,  540,  545,  553,  564,  567,  569,  572,  573,
        576,  578,  581,  583,  584,  586,  588,  595,  597,  598,  602,
        604,  611,  615,  622,  630,  637,  641,  648,  655,  660,  663,
        665,  667,  672,  681,  694,  698,  706,  708,  709,  720,  732,
        736,  741,  745,  747,  748,  749,  750,  759,  762,  764,  765,
        772,  774,  775,  789,  796,  800,  811,  812,  816,  819,  821,
        824,  828,  830,  833,  838,  839,  843,  849,  851,  856,  881,
        888,  893,  908,  913,  917,  923,  927,  944,  946,  952,  961,
        984,  988,  991,  999, 1004, 1009, 1029, 1033, 1043, 1044, 1050,
       1069, 1072, 1074, 1076, 1079, 1081, 1100, 1101, 1104, 1108, 1111,
       1117, 1119, 1122, 1123, 1124, 1125, 1138, 1141, 1143, 1144, 1145,
       1147, 1150, 1154, 1155, 1162, 1163, 1164, 1166, 1170, 1172, 1173,
       1190, 1197, 1199, 1204, 1223, 1230, 1235, 1243, 1244, 1249, 1257,
       1263, 1264, 1265, 1272, 1277, 1279, 1284, 1293, 1299, 1300, 1311,
       1317, 1325, 1328, 1329, 1331, 1344, 1345, 1349, 1359, 1372, 1377,
       1379, 1382, 1387, 1391, 1392, 1397, 1403, 1407, 1422, 1430, 1434,
       1438, 1440])), (array([   0,    1,    4, ..., 1437, 1438, 1440]), array([   2,    3,   23,   26,   31,   37,   38,   39,   50,   69,   73,
         74,   77,   79,   83,   87,   91,   99,  101,  105,  113,  124,
        125,  127,  131,  137,  141,  142,  144,  152,  153,  156,  158,
        171,  175,  176,  205,  209,  215,  225,  228,  231,  234,  244,
        248,  251,  258,  260,  265,  268,  275,  279,  286,  291,  292,
        297,  298,  301,  303,  315,  316,  318,  328,  330,  337,  338,
        341,  343,  346,  348,  354,  357,  359,  365,  366,  372,  373,
        380,  386,  388,  393,  406,  409,  410,  415,  418,  425,  431,
        439,  445,  448,  453,  454,  469,  474,  479,  489,  508,  513,
        518,  521,  531,  537,  542,  543,  560,  565,  566,  574,  589,
        590,  593,  600,  610,  612,  619,  626,  628,  633,  634,  645,
        654,  658,  659,  664,  666,  670,  673,  678,  680,  682,  683,
        685,  689,  691,  695,  699,  700,  705,  713,  716,  719,  724,
        730,  731,  740,  752,  754,  770,  782,  785,  793,  799,  801,
        805,  807,  813,  814,  823,  825,  827,  836,  840,  841,  848,
        850,  855,  862,  863,  878,  883,  885,  889,  892,  898,  899,
        901,  902,  903,  910,  924,  925,  929,  934,  937,  945,  955,
        956,  960,  964,  970,  973,  974,  975,  981,  985, 1006, 1007,
       1014, 1015, 1017, 1020, 1021, 1023, 1042, 1047, 1049, 1051, 1053,
       1055, 1063, 1075, 1083, 1085, 1086, 1088, 1090, 1097, 1107, 1112,
       1113, 1114, 1116, 1121, 1128, 1135, 1139, 1149, 1153, 1157, 1158,
       1159, 1160, 1165, 1185, 1198, 1200, 1202, 1208, 1212, 1226, 1227,
       1228, 1231, 1238, 1245, 1250, 1251, 1253, 1259, 1262, 1268, 1269,
       1283, 1285, 1286, 1288, 1289, 1290, 1292, 1305, 1306, 1312, 1316,
       1319, 1322, 1330, 1333, 1334, 1347, 1348, 1352, 1354, 1358, 1361,
       1366, 1369, 1380, 1383, 1402, 1411, 1415, 1416, 1418, 1420, 1425,
       1436, 1439])), (array([   0,    1,    2, ..., 1438, 1439, 1440]), array([   4,    6,    8,    9,   13,   14,   16,   22,   28,   29,   35,
         46,   47,   49,   51,   58,   65,   66,   68,   70,   75,   80,
         85,   88,   90,  103,  109,  110,  112,  122,  126,  130,  135,
        143,  167,  169,  172,  178,  180,  193,  195,  198,  199,  200,
        203,  204,  208,  212,  220,  223,  224,  240,  252,  255,  256,
        264,  269,  272,  274,  276,  280,  284,  294,  295,  302,  307,
        309,  320,  321,  325,  334,  342,  344,  345,  349,  352,  378,
        384,  385,  392,  394,  395,  398,  404,  408,  419,  424,  427,
        444,  447,  450,  456,  459,  466,  470,  471,  475,  477,  483,
        490,  491,  494,  495,  506,  511,  514,  519,  524,  525,  529,
        541,  547,  549,  559,  568,  579,  582,  587,  591,  592,  594,
        596,  599,  606,  607,  608,  613,  614,  616,  620,  627,  629,
        631,  643,  646,  653,  661,  671,  675,  676,  686,  688,  696,
        703,  704,  707,  722,  725,  729,  739,  753,  760,  771,  778,
        781,  784,  786,  790,  802,  804,  808,  817,  822,  831,  832,
        844,  854,  858,  860,  865,  871,  872,  874,  877,  886,  894,
        895,  896,  900,  906,  909,  911,  915,  916,  919,  926,  928,
        930,  935,  939,  940,  947,  948,  949,  953,  957,  958,  959,
        965,  967,  968,  971,  972,  976,  978,  979,  990,  992,  996,
       1001, 1002, 1011, 1022, 1036, 1039, 1041, 1052, 1058, 1062, 1064,
       1070, 1073, 1078, 1093, 1094, 1095, 1098, 1106, 1118, 1127, 1129,
       1130, 1131, 1132, 1133, 1148, 1161, 1167, 1171, 1175, 1191, 1195,
       1196, 1214, 1222, 1224, 1225, 1237, 1241, 1242, 1246, 1252, 1275,
       1276, 1280, 1297, 1301, 1303, 1304, 1308, 1313, 1314, 1318, 1321,
       1335, 1336, 1338, 1341, 1353, 1362, 1363, 1364, 1368, 1370, 1371,
       1376, 1385, 1399, 1401, 1405, 1408, 1410, 1419, 1424, 1428, 1429,
       1431, 1433]))]
results= [ 11.74213791  11.96474171  12.10428143 ...,  12.03380585  11.67877102
  12.37178898]

In [ ]:
results = np.expm1(results)

In [18]:
print("results=",results)
results = pd.DataFrame(results)
results = pd.concat([id,results], axis=1)
results.columns =["Id","SalePrice"]
print("results=",results)
results.to_csv("./ensembled_results.csv", index = False)

results= [ 125759.921875  157115.3125    180642.625    ...,  168349.90625
  118038.078125  236046.65625 ]
results=         Id      SalePrice
0     1461  125759.921875
1     1462  157115.312500
2     1463  180642.625000
3     1464  197714.406250
4     1465  192241.250000
5     1466  167046.000000
6     1467  189112.125000
7     1468  168593.812500
8     1469  194693.656250
9     1470  125454.218750
10    1471  186688.187500
11    1472   94655.039062
12    1473   96320.859375
13    1474  153493.734375
14    1475  106779.976562
15    1476  392270.031250
16    1477  245875.406250
17    1478  248936.296875
18    1479  282734.750000
19    1480  514457.093750
20    1481  341050.906250
21    1482  206747.187500
22    1483  180842.562500
23    1484  164919.515625
24    1485  176022.875000
25    1486  197346.687500
26    1487  322820.406250
27    1488  233867.781250
28    1489  196300.968750
29    1490  229678.796875
...    ...            ...
1429  2890   75054.468750
1430  2891  139185.453125
1431  2892   33230.832031
1432  2893   74879.156250
1433  2894   36026.636719
1434  2895  318453.875000
1435  2896  304144.437500
1436  2897  205956.281250
1437  2898  150579.718750
1438  2899  208748.625000
1439  2900  155996.890625
1440  2901  195067.781250
1441  2902  182080.609375
1442  2903  317690.375000
1443  2904  335088.750000
1444  2905   75708.882812
1445  2906  197584.156250
1446  2907  120199.281250
1447  2908  131445.218750
1448  2909  149943.750000
1449  2910   80689.421875
1450  2911   80458.359375
1451  2912  150918.000000
1452  2913   79543.125000
1453  2914   77271.437500
1454  2915   85284.093750
1455  2916   81492.226562
1456  2917  168349.906250
1457  2918  118038.078125
1458  2919  236046.656250

[1459 rows x 2 columns]

In [16]:
results

array([ 125759.921875,  157115.3125  ,  180642.625   , ...,  168349.90625 ,
        118038.078125,  236046.65625 ], dtype=float32)

In [17]:
id

0       1461
1       1462
2       1463
3       1464
4       1465
5       1466
6       1467
7       1468
8       1469
9       1470
10      1471
11      1472
12      1473
13      1474
14      1475
15      1476
16      1477
17      1478
18      1479
19      1480
20      1481
21      1482
22      1483
23      1484
24      1485
25      1486
26      1487
27      1488
28      1489
29      1490
        ...
1429    2890
1430    2891
1431    2892
1432    2893
1433    2894
1434    2895
1435    2896
1436    2897
1437    2898
1438    2899
1439    2900
1440    2901
1441    2902
1442    2903
1443    2904
1444    2905
1445    2906
1446    2907
1447    2908
1448    2909
1449    2910
1450    2911
1451    2912
1452    2913
1453    2914
1454    2915
1455    2916
1456    2917
1457    2918
1458    2919
Name: Id, dtype: int64